### ISSUE TITLE
Not working on Chrome browser

### ISSUE THREAD

**Issue by androyt1** [saadhaxxan/Nodejs-JWT-Cookies-Authentication#1]
This works perfectly on localhost but have browser issues when on real servers...tested on heroku..cookie isn't retrieved.

**Comment by saadhaxxan** [comment]
I didn't test it on Heroku please refer to the below link this should solve the problem.

https://www.reddit.com/r/node/comments/8jc67w/cannot_set_a_cookie_through_express_on_heroku/?utm_source=amp&utm_medium=&utm_content=post_body

I will try making this compatible on Heroku soon.

**Comment by androyt1** [comment]
Ok cool
